columnSuffix: null
handle: richtext
instructions: null
name: Richtext
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: a710df0a-1928-4ca9-ab8d-6cd7d0b2ec49 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
